# Rubyのバージョンを指定
AllCops:
  TargetRubyVersion: 2.5

# Railsモードで動作
Rails:
  Enabled: true

# １メソッド最大15行
Metrics/MethodLength:
  Max: 15

# 日本語コメントを許可
Style/AsciiComments:
  Enabled: false

# ドキュメントコメント無しを許容
Style/Documentation:
  Enabled: false

# freezeしていない文字列リテラルを許可
Style/FrozenStringLiteralComment:
  Enabled: false

# 冗長なselfを許可
Style/RedundantSelf:
  Enabled: false

# クラス、モジュールの定義時にネストを使わないことを許容
Style/ClassAndModuleChildren:
  Enabled: false

# private/protected は一段深くインデントする
Layout/IndentationConsistency:
  EnforcedStyle: rails

# 数値を３桁ごとに_で繋がなくても良い
Style/NumericLiterals:
  Enabled: false

# private/protectedメソッドのインデントを許可
Style/IndentationConsistency:
  Enabled: false

# 一行のみのif式を許可
Style/GuardClause:
  Enabled: false

# ABCSize制限を緩和
Metrics/AbcSize:
  Max: 20

# テストコードではブロック長超過を許容
Metrics/BlockLength:
  Exclude:
      - 'spec/**/*.rb'

# 子クラスでの実装に期待したメソッド呼び出しを許可
Rails/LexicallyScopedActionFilter:
  Enabled: false
