version: 2.1
jobs:
  build:
    docker:
      - image: ruby:2.5.1
    working_directory: /usr/local/pankara
    steps:
      - checkout
      - run:
        name: runテスト
        command: echo 'hoge'

