version: 2.1
jobs:
  build:
    docker:
      - image: ruby:2.5.1
    working_directory: /usr/local/pankara
    steps:
      - checkout
      - run:
          name: パッケージを最新化
          command: |
            apt-get update -qq
            apt-get install -y mysql-client build-essential
