version: 2.1
jobs:
  build:
    docker:
      - image: ruby:2.5.1
    working_directory: /usr/local/pankara
    steps:
      - checkout
      - run:
          name: apt-get install
          command: |
            apt-get update -qq
            apt-get install -y mysql-client build-essential
      - run:
          name: bundle install
          command: bundle install
      - run:
          name: rspec
          command: bundle exec rspec -f d
