default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  host: pankara_db
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  password: <%= Rails.application.credentials.dig(:development, :database, :password) %>
  database: pankara_development

test:
  <<: *default
  host: <%= ENV['CI'] ? '127.0.0.1' : 'pankara_db' %>
  database: pankara_test
  password: 1q2w3e4r

production:
  <<: *default
  database: pankara_production
  password: <%= Rails.application.credentials.dig(:production, :database, :password) %>
