default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  host: pankara_db
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  password: <%= Rails.application.credentials.dig(:development, :database, :password) %>
  database: pankara_development

test:
  <<: *default
  password: <%= Rails.application.credentials.dig(:development, :database, :password) %>
  database: pankara_test

production:
  <<: *default
  database: pankara_production
  username: pankara
  password: <%= Rails.application.credentials.dig(:production, :database, :password) %>
